### ISSUE TITLE
Assignment 4 - Show image in the readme.md

### ISSUE THREAD

**Issue by ProfPollati** [Bloomfield-FA15-CAT238/FirstRepoJohnLandi#1]
For the link to the image you added, I wanted it to appear in the readme.md when view from GitHub

**Comment by JohnLandi** [comment]
Which image? I have done that for the the jpeg. Was it for the original image that we uploaded in the first project or did the confusion come from me having a gif and a jpeg. I also used a URL shorten-er for the link.

**Comment by ProfPollati** [comment]
The Assets/README.md should shoud the image "funny-pictures-cat-hates-pickle.jpg" when viewed from GitHub, not a link to "https://goo.gl/hn2tdO"

**Comment by ProfPollati** [comment]
I also updated the [Assignment4and5](https://github.com/Bloomfield-FA15-CAT238/Assignments/tree/master/Assignment4and5) page with more clarification

**Comment by JohnLandi** [comment]
Thank you!
